### ISSUE TITLE
Titles of Duplicate and Edit Icon of the dropped fields

### ISSUE THREAD

**Issue by albu77** [kevinchappell/formBuilder-languages#12] opened 2017-08-05 07:45 UTC
Edit has the wrong text of Hide
Dupplicate has undefined title
My locale is french but I didn't find the translation which I think are missing

**Comment by kevinchappell** [comment] 2019-03-30 00:54
These fields likely need translation.

**Comment by kevinchappell** [comment] 2024-05-29 23:31
im not able to reproduce this issue and it seems quite old so closing.

**Closed by kevinchappell** 2024-05-29 23:31 UTC
